import { db } from '../src/lib/db';

const INITIAL_COMPETITIONS = [
  {
    slug: 'nova-cup-volga',
    title: 'NOVA CUP — Волга. Кубок открытия сезона',
    shortName: 'NOVA CUP — Волга',
    name: 'NOVA CUP — Волга. Кубок открытия сезона',
    description: 'NOVA CUP — Волга традиционно открывает соревновательный сезон Альянса. Экипажи из 12 регионов встретятся на воде Астраханской области — одном из самых техничных и рыбных полигонов страны.',
    discipline: 'spinning',
    disciplineLabel: 'Спиннинг, лодка',
    location: 'Астраханская область',
    region: 'Юг России',
    dateLabel: '13–15 июня 2026',
    startDate: new Date('2026-06-13T00:00:00Z'),
    endDate: new Date('2026-06-15T00:00:00Z'),
    date: new Date('2026-06-13T00:00:00Z'),
    maxEntries: 80,
    maxParticipants: 80,
    fee: 5000,
    entryFee: 5000,
    prizeFund: '2 000 000 ₽',
    status: 'upcoming',
    format: 'Экипажи, 2 спортсмена',
    entryType: 'team',
    organizer: 'NOVA Anglers Alliance',
    contact: 'volga@nova-anglers.ru',
    days: 3,
    pointsMultiplier: '×1.5',
  },
  {
    slug: 'bereg-rossii-1',
    title: 'Берег России — этап 1',
    shortName: 'Берег России — этап 1',
    name: 'Берег России — этап 1',
    description: 'Первый этап берегового кубка сезона. Личный зачёт, ловля со стационарных точек побережья Финского залива.',
    discipline: 'spinning',
    disciplineLabel: 'Береговой спиннинг',
    location: 'Ленинградская область',
    region: 'Северо-Запад',
    dateLabel: '27 июня 2026',
    startDate: new Date('2026-06-27T00:00:00Z'),
    endDate: new Date('2026-06-27T00:00:00Z'),
    date: new Date('2026-06-27T00:00:00Z'),
    maxEntries: 60,
    maxParticipants: 60,
    fee: 2500,
    entryFee: 2500,
    prizeFund: '600 000 ₽',
    status: 'upcoming',
    format: 'Личный зачёт',
    entryType: 'individual',
    organizer: 'NOVA Anglers Alliance',
    contact: 'shore@nova-anglers.ru',
    days: 1,
    pointsMultiplier: '×1.0',
  },
  {
    slug: 'nova-don-summer',
    title: 'NOVA Дон — летний рубеж',
    shortName: 'NOVA Дон — летний рубеж',
    name: 'NOVA Дон — летний рубеж',
    description: 'Летний этап на Дону — техничная короткая дистанция, важный рубеж перед серединой сезона.',
    discipline: 'spinning',
    disciplineLabel: 'Лодка',
    location: 'Ростовская область',
    region: 'Юг России',
    dateLabel: '11 июля 2026',
    startDate: new Date('2026-07-11T00:00:00Z'),
    endDate: new Date('2026-07-11T00:00:00Z'),
    date: new Date('2026-07-11T00:00:00Z'),
    maxEntries: 70,
    maxParticipants: 70,
    fee: 4000,
    entryFee: 4000,
    prizeFund: '1 200 000 ₽',
    status: 'upcoming',
    format: 'Экипажи, 2 спортсмена',
    entryType: 'team',
    organizer: 'NOVA Anglers Alliance',
    contact: 'don@nova-anglers.ru',
    days: 1,
    pointsMultiplier: '×1.2',
  },
  {
    slug: 'kubok-kaspiya',
    title: 'Кубок Каспия',
    shortName: 'Кубок Каспия',
    name: 'Кубок Каспия',
    description: 'Квалификационный этап южного побережья Каспия, открыт для личного зачёта.',
    discipline: 'spinning',
    disciplineLabel: 'Спиннинг с лодок',
    location: 'Дагестан',
    region: 'Юг России',
    dateLabel: '25 июля 2026',
    startDate: new Date('2026-07-25T00:00:00Z'),
    endDate: new Date('2026-07-25T00:00:00Z'),
    date: new Date('2026-07-25T00:00:00Z'),
    maxEntries: 60,
    maxParticipants: 60,
    fee: 3000,
    entryFee: 3000,
    prizeFund: '800 000 ₽',
    status: 'upcoming',
    format: 'Личный зачёт',
    entryType: 'individual',
    organizer: 'NOVA Anglers Alliance',
    contact: 'kaspiy@nova-anglers.ru',
    days: 1,
    pointsMultiplier: '×1.0',
  },
  {
    slug: 'nova-fly-karelia',
    title: 'NOVA Fly — мушка и нахлыст',
    shortName: 'NOVA Fly — Карелия',
    name: 'NOVA Fly — мушка и нахлыст',
    description: 'Нишевый этап для нахлыстовиков на карельских озёрах.',
    discipline: 'trout',
    disciplineLabel: 'Нахлыст / Форель',
    location: 'Карелия',
    region: 'Северо-Запад',
    dateLabel: '8 августа 2026',
    startDate: new Date('2026-08-08T00:00:00Z'),
    endDate: new Date('2026-08-08T00:00:00Z'),
    date: new Date('2026-08-08T00:00:00Z'),
    maxEntries: 40,
    maxParticipants: 40,
    fee: 2000,
    entryFee: 2000,
    prizeFund: '400 000 ₽',
    status: 'upcoming',
    format: 'Личный зачёт',
    entryType: 'individual',
    organizer: 'NOVA Anglers Alliance',
    contact: 'fly@nova-anglers.ru',
    days: 1,
    pointsMultiplier: '×0.8',
  },
];

async function seed() {
  console.log('Seeding initial competitions into DB...');
  for (const c of INITIAL_COMPETITIONS) {
    await db.competition.upsert({
      where: { slug: c.slug },
      update: c,
      create: c,
    });
  }
  const count = await db.competition.count();
  console.log(`Successfully seeded! Total competitions in DB: ${count}`);
}

seed().catch(console.error).finally(() => process.exit(0));
